sync graph, lab topology manage db, better result type (#1)
Co-authored-by: sagi <sagi@quantum-machines.co>

diff --git a/.github/workflows/on-pull-request.yml b/.github/workflows/on-pull-request.yml
--- a/.github/workflows/on-pull-request.yml
+++ b/.github/workflows/on-pull-request.yml
@@ -44,22 +44,24 @@ jobs:
       - name: check tests results
         run: |
           TEST_FAILED=0
-          if [ ${{steps.back-check.outcome}} == 'failure' ]; then
-             echo "black failed"
+          if [ ${{steps.back-check.outcome}} != 'success' ]; then
+             echo "black failed, result was: ${{steps.back-check.outcome}}"
              TEST_FAILED=1
           else
             echo "black passed"
           fi
-          if [ ${{steps.flake8.outcome}} == 'failure' ]; then
-             echo "flake8 failed"
+          if [ ${{steps.flake8.outcome}} != 'success' ]; then
+             echo "flake8 failed, result was: ${{steps.flake8.outcome}}"
              TEST_FAILED=1
           else
             echo "flake8 passed"
           fi
-          if [ ${{steps.pytest.outcome}} == 'failure' ]; then 
-            echo "pytest failed"
+          if [ ${{steps.pytest.outcome}} != 'success' ]; then 
+            echo "pytest failed, result was: ${{steps.pytest.outcome}}"
             TEST_FAILED=1
           else
             echo "pytest passed"
           fi
-          [ ${TEST_FAILED} != 0 ] && exit 1
+          if [ ${TEST_FAILED} -ne 0 ]; then
+            exit 1
+          fi
